# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SNGL5eK8Fny_XKiUM-ZgEvwSxbmHz7S_
"""

pip install streamlit

import pandas as pd
customer_data = pd.read_csv("customer_review_clusters.csv")
customer_data

import streamlit as st
import pandas as pd

# -----------------------------
# Page Config
# -----------------------------
st.set_page_config(
    page_title="Customer Review Clustering",
    layout="wide"
)

# -----------------------------
# Title
# -----------------------------
st.title("🛍️ Customer Review Clustering for Market Research")
st.write(
    "This Streamlit app displays clustered customer reviews generated using "
    "Machine Learning (K-Means)."
)

# -----------------------------
# Load Data (Safe)
# -----------------------------
@st.cache_data
def load_data():
    try:
        df = pd.read_csv("customer_review_clusters.csv")
        return df
    except FileNotFoundError:
        st.error("❌ customer_review_clusters.csv file not found in the project folder.")
        st.stop()

df = load_data()

# -----------------------------
# Column Validation (ERROR‑PROOF)
# -----------------------------
required_columns = ["review_content", "cluster"]

for col in required_columns:
    if col not in df.columns:
        st.error(f"❌ Required column missing: {col}")
        st.stop()

# -----------------------------
# Handle cluster_name safely
# -----------------------------
if "cluster_name" not in df.columns:
    st.warning(
        "⚠️ 'cluster_name' column not found. "
        "Using numeric cluster labels instead."
    )
    df["cluster_name"] = df["cluster"].astype(str)

# -----------------------------
# Sidebar Filters
# -----------------------------
st.sidebar.header("🔍 Filters")

cluster_names = sorted(df["cluster_name"].unique())

selected_cluster = st.sidebar.selectbox(
    "Select Cluster",
    cluster_names
)

# -----------------------------
# Dataset Preview
# -----------------------------
st.subheader("📊 Clustered Dataset Preview")
st.dataframe(df.head(20), use_container_width=True)

# -----------------------------
# Filtered Reviews
# -----------------------------
filtered_df = df[df["cluster_name"] == selected_cluster]

st.subheader(f"🧠 Reviews in Cluster: **{selected_cluster}**")
st.write(f"Total Reviews: **{len(filtered_df)}**")

# -----------------------------
# Display Reviews Safely
# -----------------------------
if len(filtered_df) == 0:
    st.info("No reviews available for this cluster.")
else:
    for i, review in enumerate(
        filtered_df["review_content"].head(10), start=1
    ):
        st.markdown(f"**{i}.** {review}")

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")
st.caption("ML Project • Streamlit Deployment • Customer Review Clustering")